### ISSUE TITLE
Bug with CE's

### ISSUE THREAD

**Issue by iZeaoGamer** [CubePM/MysteryBox#10]
Now, I just noticed the CE works with crates, but the enchantments / CE's don't show up on the weapons, armors, etc. It shows up for Vanilla Enchants, but not the CE's. This isn't a bug with PiggyCustomEnchants, as when I try and use it with /ce, it works perfectly. It's only with crates. Yes, I've added in the ID as you asked, but this seems to be a bug with MysteryBox. Not entirely sure what's the cause of this, but I'm hoping you could fix this, thanks.

**Comment by TheAz928** [comment]
It is a bug with pig CE, bcz it doesn't have auto rename listener, don't expect every plugin to fix other plugin's bugs/issues

**Comment by TheAz928** [comment]
Do not create further issues about this

**Comment by iZeaoGamer** [comment]
This works with any other plugin I use, but not this one. So don't expect me not to report an issue that could potentially have relations to this plugin. Thanks for nothing.

**Comment by iZeaoGamer** [comment]
Know what? I really like where you're going with this plugin, but at least be a bit less rude about other player's issues. Actually be nice about it instead of telling them things that it's obviously known - Be a bit less rude about what you do with other people's issues, or you'll end up no where. Just a little advice from me before being rude again.

**Comment by TheAz928** [comment]
The thing is the thing, it's not this plugins issue, yes of course this issue is "replated" to the plugin. Bit it's not "the plugins" issue

**Comment by TheAz928** [comment]
I'll ask @DaPigGuy to add a auto name fix listener for his plug

**Comment by iZeaoGamer** [comment]
Okay, thanks.
