### ISSUE TITLE
Invalid mysterybox id

### ISSUE THREAD

**Issue by SuperAdam47** [CubePM/MysteryBox#12]
/mb create common

**Comment by TheAz928** [comment]
invalid issue also

**Comment by SuperAdam47** [comment]
![image](https://user-images.githubusercontent.com/16169771/44648242-15062b00-a9e9-11e8-9736-f94609682816.png)
@TheAz928

**Comment by SuperAdam47** [comment]
Config file ;


---
# Developed by TheAz928
# MysteryBox configuration file

# Message title/prefix
prefix: "[GizemliKutu]"

# Mystery Box text update time (in seconds)
text.update: 3

# Version, recommend to not change
version: 1

# Mystery box configuration
boxes:
    - name: "&6&lEfsanevi Oy Kasası"
      box.id: common
      key:
          item: "tripwire_hook:1"
          name: "&7[&aKey&7]&r Efsanevi Oy"
          lore:
              - "&7Tip: &aOy"
              - "&7Source: &cunknown"
              - " "
              - "&l&6Efsanevi Oy kasası &fAnahtarı"
      rgb:
          R: 255
          G: 255
          B: 255
      items:
          - item: "bread:0:10"
            chance: 30
          - item: "322:0:20"
            chance: 20
          - item: "466:0:1"
            chance: 15
          - item: "49:0:10"
            chance: 40
          - item: "iron_ingot:0:32"
            chance: 80
          - item: "gold_ingot:0:32"
            chance: 60
          - item: "bedrock:0:1"
            chance: 5
    - name: "&b&lGizemli Şans Kasası"
      box.id: loot
      key:
          item: "tripwire_hook:2"
          name: "&7[&aKey&7]&r Loot"
          lore:
              - "&7Tip: &bŞans"
              - "&7Source: &cunknown"
              - " "
              - "&l&bŞans Kasası &fAnahtarı"
      rgb:
          R: 255
          G: 200
          B: 200
      items:
          - item: "diamond:0:10"
            chance: 80
          - item: "466:0:20"
            chance: 20
          - item: "diamond_block:0:5"
            chance: 15
          - item: "49:0:64"
            chance: 40
          - item: "iron_block:0:32"
            chance: 80
          - item: "wheat:0:64"
            chance: 50
          - item: "diamond_block:0:64"
            chance: 5
          - item: "bedrock:0:20"
            chance: 5

...

**Comment by SuperAdam47** [comment]
@TheAz928
