### ISSUE TITLE
Overlapping text and other issue

### ISSUE THREAD

**Issue by ManiakMCPE** [CubePM/MysteryBox#20]
If you stay on the server for about 5 minutes, the floating texts start to overlap eachother. There is also a glitch where if you are not in the loaded chunk when something it opened, it stays there until you relog. https://imgur.com/a/FNnWTxM

**Comment by TheAz928** [comment]
Probs some client issue, should be fine if you relog

**Comment by ManiakMCPE** [comment]
this isn't a client side issue, it's still not fixed.
