### ISSUE TITLE
README is not worth reading - at least not for me

### ISSUE THREAD

**Issue by robske110** [CubePM/MysteryBox#8]
The README (and subsequently your description on poggit) does not include any How to use instructions. It might be a good idea to update the readme and the description to give a quick introduction and overview for users.

**Comment by TheAz928** [comment]
bruh check wiki

**Comment by TheAz928** [comment]
@robske110 https://github.com/CubePM/MysteryBox/wiki

**Comment by robske110** [comment]
Ah, didn‘t see that. I’d recommend to include at least some portions of it in the poggit description (it has sectiona, and even supports subsections) and include a link to the wiki in the description.
