### ISSUE TITLE
No Custom enchants support?

### ISSUE THREAD

**Issue by iZeaoGamer** [CubePM/MysteryBox#9]
Hi, I tried using Custom Enchants support (as said in README), and the custom enchants (as PiggyCustomEnchants), they don't seem to work, like example: drunk, DeathBringer, etc. I've tried the following: IDS, CE Names, lowercasing it, etc. But they don't seem to work. Any ideas? Or if you haven't yet implemented this, would it be possible if you add PiggyCustomEnchants support to this plugin? Thanks, it'd be much appreciated.

**Comment by ghost** [comment]
you can ask @TheAz928 to implement it or do it yourself it's not that hard

**Comment by TheAz928** [comment]
This works fine, could you provide the IDs you used or the config? Or I'm closing this issue, works totally fine for me

**Comment by TheFixerDevelopment** [comment]
---
# Developed by TheAz928
# MysteryBox configuration file

# Message title/prefix
prefix: "[Mysterybox]"

# Mystery Box text update time (in seconds)
text.update: 3

# Version, recommend to not change
version: 1

# Mystery box configuration
boxes:
    - name: "&6&lCommon Mystery Box"
      box.id: common
      key:
          item: "tripwire_hook:1"
          name: "&8[Key]&r Common"
          lore:
              - "&7Type: &acommon"
              - "&7Source: &cunknown"
              - " "
              - "&fUsed to open &6&lCommon Mystery Box"
      rgb:
          R: 255
          G: 255
          B: 255
      items:
          - item: "298:0:1:&aCommon Cap:protection:1"
            chance: 30
          - item: "299:0:1:&aCommon ChestPlate:protection:1"
            chance: 20
          - item: "300:0:1:&aCommon Leggings:protection:1"
            chance: 15
          - item: "301:0:1:&aCommon Boots:protection:1"
            chance: 40
          - item: "49:0:5:&aCommon Obsidian"
            chance: 80
          - item: "270:0:1:&aCommon Pickaxe:efficiency:3:silk_touch:1"
            chance: 60
          - item: "bedrock:0:1"
            chance: 5
    - name: "&a&lVote &6Mystery Box"
      box.id: vote
      key:
          item: "tripwire_hook:2"
          name: "&8[Key]&r Vote"
          lore:
              - "&7Type: &bVote"
              - "&7Source: &cunknown"
              - " "
              - "&fUsed to open &b&lMystery Vote Box"
      rgb:
          R: 255
          G: 200
          B: 200
      items:
          - item: "diamond_helmet:0:1:&bVote &3Helmet:protection:5:drunk:1:anti-knockback:1:armored:1"
            chance: 20
          - item: "diamond_chestplate:0:1:&bVote &3ChestPlate:protection:5:drunk:1:anti-knockback:1:armored:1"
            chance: 20
          - item: "diamond_leggings:0:1:&bVote &3Leggings:protection:5:drunk:1:anti-knockback:1:armored:1"
            chance: 20
          - item: "diamond_boots:0:1:&bVote &3Boots:protection:5:drunk:1:anti-knockback:1:armored:1"
            chance: 20
          - item: "diamond_sword:0:1:&bVote &3Sword:sharpness:10:deathbringer:1"
            chance: 16
          - item: "diamond_axe:0:1:&bVote &3Axe:sharpness:10:deathbringer:1"
            chance: 10
          - item: "diamond_pickaxe:0:1:&bVote &3Pickaxe:efficiency:1:driller:1"
            chance: 15
          - item: "diamond_shovel:0:1:&bVote &3Shovel:efficiency:15:silk_touch:1:Driller:1:Energizing:1:Haste:1"
            chance: 15
          - item: "52:32:10:&bVote &3Zombie Spawners"
            chance: 10
          - item: "52:34:10:&bVote &3Skeleton Spawners"
            chance: 10
          - item: "52:20:10:&bVote &3Iron Golems Spawners"
            chance: 5
          - item: "52:43:10:&bVote &3Blaze Spawners"
            chance: 10
          - item: "466:0:20:&bVote &3Enchanted Golden Apples"
            chance: 5
          - item: "7:0:10:&bVote &3Bedrock"
            chance: 4

...

**Comment by iZeaoGamer** [comment]
This is the config here:
---
# Developed by TheAz928
# MysteryBox configuration file

# Message title/prefix
prefix: "[Mysterybox]"

# Mystery Box text update time (in seconds)
text.update: 3

# Version, recommend to not change
version: 1

# Mystery box configuration
boxes:
    - name: "&6&lCommon Mystery Box"
      box.id: common
      key:
          item: "tripwire_hook:1"
          name: "&8[Key]&r Common"
          lore:
              - "&7Type: &acommon"
              - "&7Source: &cunknown"
              - " "
              - "&fUsed to open &6&lCommon Mystery Box"
      rgb:
          R: 255
          G: 255
          B: 255
      items:
          - item: "298:0:1:&aCommon Cap:protection:1"
            chance: 30
          - item: "299:0:1:&aCommon ChestPlate:protection:1"
            chance: 20
          - item: "300:0:1:&aCommon Leggings:protection:1"
            chance: 15
          - item: "301:0:1:&aCommon Boots:protection:1"
            chance: 40
          - item: "49:0:5:&aCommon Obsidian"
            chance: 80
          - item: "270:0:1:&aCommon Pickaxe:efficiency:3:silk_touch:1"
            chance: 60
          - item: "bedrock:0:1"
            chance: 5
    - name: "&a&lVote &6Mystery Box"
      box.id: vote
      key:
          item: "tripwire_hook:2"
          name: "&8[Key]&r Vote"
          lore:
              - "&7Type: &bVote"
              - "&7Source: &cunknown"
              - " "
              - "&fUsed to open &b&lMystery Vote Box"
      rgb:
          R: 255
          G: 200
          B: 200
      items:
          - item: "diamond_helmet:0:1:&bVote &3Helmet:protection:5:drunk:1:anti-knockback:1:armored:1"
            chance: 20
          - item: "diamond_chestplate:0:1:&bVote &3ChestPlate:protection:5:drunk:1:anti-knockback:1:armored:1"
            chance: 20
          - item: "diamond_leggings:0:1:&bVote &3Leggings:protection:5:drunk:1:anti-knockback:1:armored:1"
            chance: 20
          - item: "diamond_boots:0:1:&bVote &3Boots:protection:5:drunk:1:anti-knockback:1:armored:1"
            chance: 20
          - item: "diamond_sword:0:1:&bVote &3Sword:sharpness:10:deathbringer:1"
            chance: 16
          - item: "diamond_axe:0:1:&bVote &3Axe:sharpness:10:deathbringer:1"
            chance: 10
          - item: "diamond_pickaxe:0:1:&bVote &3Pickaxe:efficiency:1:driller:1"
            chance: 15
          - item: "diamond_shovel:0:1:&bVote &3Shovel:efficiency:15:silk_touch:1:Driller:1:Energizing:1:Haste:1"
            chance: 15
          - item: "52:32:10:&bVote &3Zombie Spawners"
            chance: 10
          - item: "52:34:10:&bVote &3Skeleton Spawners"
            chance: 10
          - item: "52:20:10:&bVote &3Iron Golems Spawners"
            chance: 5
          - item: "52:43:10:&bVote &3Blaze Spawners"
            chance: 10
          - item: "466:0:20:&bVote &3Enchanted Golden Apples"
            chance: 5
          - item: "7:0:10:&bVote &3Bedrock"
            chance: 4

...

**Comment by TheAz928** [comment]
please note: name is not supported for custom enchants, please use ids. I'll now mark this as invalid and close

**Comment by iZeaoGamer** [comment]
I’ll try IDS again, but keep in mind - I might’ve already tried ids with no use. But I’ll let you know if it works or not. (Might be mistaken though).

**Comment by TheAz928** [comment]
Where you got the IDs from?

**Comment by TheAz928** [comment]
Make sure all the IDs are correct

**Comment by iZeaoGamer** [comment]
Basically, all the Custom enchants ID came from the PiggyCustomEnchants code (in CustomEnchantsID php file).

**Comment by iZeaoGamer** [comment]
But as I said, I’ll double check, and see if this works or not.

**Comment by iZeaoGamer** [comment]
Jus to make sure.

**Comment by iZeaoGamer** [comment]
Okay, I've tried with the following configuration settings here:
---
# Developed by TheAz928
# MysteryBox configuration file

# Message title/prefix
prefix: "[Mysterybox]"

# Mystery Box text update time (in seconds)
text.update: 3

# Version, recommend to not change
version: 1

# Mystery box configuration
boxes:
    - name: "&6&lCommon Mystery Box"
      box.id: common
      key:
          item: "tripwire_hook:1"
          name: "&8[Key]&r Common"
          lore:
              - "&7Type: &acommon"
              - "&7Source: &cunknown"
              - " "
              - "&fUsed to open &6&lCommon Mystery Box"
      rgb:
          R: 255
          G: 255
          B: 255
      items:
          - item: "298:0:1:&aCommon Cap:protection:1"
            chance: 30
          - item: "299:0:1:&aCommon ChestPlate:protection:1"
            chance: 20
          - item: "300:0:1:&aCommon Leggings:protection:1"
            chance: 15
          - item: "301:0:1:&aCommon Boots:protection:1"
            chance: 40
          - item: "49:0:5:&aCommon Obsidian"
            chance: 80
          - item: "270:0:1:&aCommon Pickaxe:efficiency:3:silk_touch:1"
            chance: 60
          - item: "bedrock:0:1"
            chance: 5
    - name: "&a&lVote &6Mystery Box"
      box.id: vote
      key:
          item: "tripwire_hook:2"
          name: "&8[Key]&r Vote"
          lore:
              - "&7Type: &bVote"
              - "&7Source: &cunknown"
              - " "
              - "&fUsed to open &b&lMystery Vote Box"
      rgb:
          R: 255
          G: 200
          B: 200
      items:
          - item: "diamond_helmet:0:1:&bVote &3Helmet:protection:5:410:1:417:1:420:1"
            chance: 20
          - item: "diamond_chestplate:0:1:&bVote &3ChestPlate:protection:5:410:1:417:1:420:1"
            chance: 20
          - item: "diamond_leggings:0:1:&bVote &3Leggings:protection:5:410:1:417:1:420:"
            chance: 20
          - item: "diamond_boots:0:1:&bVote &3Boots:protection:5:drunk:1:anti-knockback:1:armored:1"
            chance: 20
          - item: "diamond_sword:0:1:&bVote &3Sword:sharpness:10:102:1"
            chance: 16
          - item: "diamond_axe:0:1:&bVote &3Axe:sharpness:10:102:1"
            chance: 10
          - item: "diamond_pickaxe:0:1:&bVote &3Pickaxe:efficiency:1:206:1"
            chance: 15
          - item: "diamond_shovel:0:1:&bVote &3Shovel:efficiency:15:silk_touch:1:206:1:202:1:207:1"
            chance: 15
          - item: "52:32:10:&bVote &3Zombie Spawners"
            chance: 10
          - item: "52:34:10:&bVote &3Skeleton Spawners"
            chance: 10
          - item: "52:20:10:&bVote &3Iron Golems Spawners"
            chance: 5
          - item: "52:43:10:&bVote &3Blaze Spawners"
            chance: 10
          - item: "466:0:20:&bVote &3Enchanted Golden Apples"
            chance: 5
          - item: "7:0:10:&bVote &3Bedrock"
            chance: 4

...
And the Custom Enchants seem to not be working, even with IDS.

**Comment by iZeaoGamer** [comment]
Ignore the rest. I've tried with The diamond sword enchantment, and they don't seem to be working.

**Comment by iZeaoGamer** [comment]
I've tried at least a few items first before doing the rest, and it doesn't seem to be working.

**Comment by iZeaoGamer** [comment]
And as the code's state, there's no coding relating to PiggyCustomEnchants - To make sure they also work with CE's aswell. As far as the codes concerned, it only works with Vanilla Enchants.
